name = "share-api"
type = "javascript"

account_id = "bc12e3978fbec832b092cd18394f9df5"

route = "share-api.repro.dev/*"
zone_id = "e7d88b916f0632589e8c54384114c06d"
compatibility_date = "2022-01-17"

kv_namespaces = [
  { binding = "SESSION", id = "92f942aac7874d9a8cccc09d642fbd7a" }
]

[env.staging]
workers_dev = true
kv_namespaces = [
  { binding = "SESSION", id = "7f4c06d4b3c143c48c338ce4fbb77790" }
]

[vars]
STORAGE_API_DEFAULT_BASE_URL = "https://api.backblaze.com"
STORAGE_API_VERSION = "v2"
STORAGE_API_KEY_ID = "00331ad9ade589b0000000003"
STORAGE_API_BUCKET_ID = "83913afd89ba6d9e75e8091b"
STORAGE_API_BUCKET_NAME = "recordings-public"

# [secrets]
# STORAGE_API_KEY
